<?php

namespace Database\Seeders;

use App\Models\Endpoint;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class EndpointSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $endpoint = [
            [
                "section" => "Authentications",
                "Endpoint" => "/api/user/register",
                "Method" => "POST",
                "Description" => "Register as User",
                "Header" => "",
                "Body" => "name, email, password",
                "Response" => "Bearer Token",
            ],
            [
                "section" => "Authentications",
                "Endpoint" => "/api/user/login",
                "Method" => "POST",
                "Description" => "Login as User",
                "Header" => "",
                "Body" => "email, password",
                "Response" => "Bearer Token",
            ],
            [
                "section" => "Authentications",
                "Endpoint" => "/api/user/logout",
                "Method" => "POST",
                "Description" => "Logout as User",
                "Header" => "bearer token",
                "Body" => "",
                "Response" => "Success",
            ],
            [
                "section" => "Authentications",
                "Endpoint" => "/api/company/register",
                "Method" => "POST",
                "Description" => "Register as Company",
                "Header" => "",
                "Body" => "name, email, password",
                "Response" => "Bearer Token",
            ],
            [
                "section" => "Authentications",
                "Endpoint" => "/api/company/login",
                "Method" => "POST",
                "Description" => "Login as Company",
                "Header" => "",
                "Body" => "email, password",
                "Response" => "Bearer Token",
            ],
            [
                "section" => "Authentications",
                "Endpoint" => "/api/company/logout",
                "Method" => "POST",
                "Description" => "Logout as Company",
                "Header" => "bearer token",
                "Body" => "",
                "Response" => "Success",
            ],
            [
                "section" => "Company Authenticated",
                "Endpoint" => "/api/auth/company/add-products",
                "Method" => "GET",
                "Description" => "Get add Products Page",
                "Header" => "bearer token",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "Company Authenticated",
                "Endpoint" => "/api/auth/company/add-products",
                "Method" => "POST",
                "Description" => "Upload Product",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "Company Authenticated",
                "Endpoint" => "/api/auth/company/product/{id}",
                "Method" => "GET",
                "Description" => "Get this Product as Company",
                "Header" => "bearer token",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "Company Authenticated",
                "Endpoint" => "/api/auth/company/product/{id}",
                "Method" => "DELETE",
                "Description" => "Delete this Product as Company",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "Company Authenticated",
                "Endpoint" => "/api/auth/company/archive-product/{id}",
                "Method" => "POST",
                "Description" => "Archive this Product as Company",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "Company Authenticated",
                "Endpoint" => "/api/auth/company/add-service",
                "Method" => "GET",
                "Description" => "Get add Services Page",
                "Header" => "bearer token",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "Company Authenticated",
                "Endpoint" => "/api/auth/company/add-service",
                "Method" => "POST",
                "Description" => "Upload Service",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "Company Authenticated",
                "Endpoint" => "/api/auth/company/service/{id}",
                "Method" => "GET",
                "Description" => "Get this Service as Company",
                "Header" => "bearer token",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "Company Authenticated",
                "Endpoint" => "/api/auth/company/service/{id}",
                "Method" => "DELETE",
                "Description" => "Delete this Service as Company",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "Company Authenticated",
                "Endpoint" => "/api/auth/company/archive-service/{id}",
                "Method" => "POST",
                "Description" => "Archive this Service as Company",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "Company Authenticated",
                "Endpoint" => "/api/auth/company/getAllProducts",
                "Method" => "GET",
                "Description" => "List my Products as company",
                "Header" => "bearer token",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "Company Authenticated",
                "Endpoint" => "/api/auth/company/getAllServices",
                "Method" => "GET",
                "Description" => "List my Services as company",
                "Header" => "bearer token",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "Guest",
                "Endpoint" => "/api/service/get/{service_id}",
                "Method" => "GET",
                "Description" => "Show this Service details",
                "Header" => "",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "Guest",
                "Endpoint" => "/api/service/latest",
                "Method" => "GET",
                "Description" => "Show Lastest Services",
                "Header" => "",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "Guest",
                "Endpoint" => "/api/service/search/{keywords}",
                "Method" => "GET",
                "Description" => "Search Service by keywords",
                "Header" => "",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "Guest",
                "Endpoint" => "/api/product/get/{product_id}",
                "Method" => "GET",
                "Description" => "Get this Product details",
                "Header" => "",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "Guest",
                "Endpoint" => "/api/product/latest",
                "Method" => "GET",
                "Description" => "Get Lastest Products",
                "Header" => "",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "Guest",
                "Endpoint" => "/api/product/search/{keywords}",
                "Method" => "GET",
                "Description" => "Search Product by keywords",
                "Header" => "",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "Guest",
                "Endpoint" => "/api/category/{id}",
                "Method" => "GET",
                "Description" => "Get By Category",
                "Header" => "",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "Guest",
                "Endpoint" => "/api/company/{id}",
                "Method" => "GET",
                "Description" => "Show Company Details",
                "Header" => "",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/company/{id}/follow",
                "Method" => "POST",
                "Description" => "Follow this Company",
                "Header" => "bearer token",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/company/{id}/unfollow",
                "Method" => "POST",
                "Description" => "unFollow this Company",
                "Header" => "bearer token",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/company/{id}/newsletter/follow",
                "Method" => "GET",
                "Description" => "Follow this Newsletter",
                "Header" => "bearer token",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/company/{id}/newsletter/unfollow",
                "Method" => "GET",
                "Description" => "unFollow this Newsletter",
                "Header" => "bearer token",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/product/{id}/favorite",
                "Method" => "GET",
                "Description" => "Save this Product",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/product/{id}/unfavorite",
                "Method" => "GET",
                "Description" => "unSave this Product",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/product/{id}/add-review",
                "Method" => "GET",
                "Description" => "Post Review in Product",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/product/{id}/delete-review",
                "Method" => "GET",
                "Description" => "get add services page",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/service/{id}/favorite",
                "Method" => "GET",
                "Description" => "Save this Service",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/service/{id}/unfavorite",
                "Method" => "GET",
                "Description" => "unSave this Service",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/service/{id}/book",
                "Method" => "GET",
                "Description" => "Book a Session",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/service/{id}/unbook",
                "Method" => "GET",
                "Description" => "Cancel Booking a Session",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/orders",
                "Method" => "GET",
                "Description" => "List my Orders",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/orders/{id}",
                "Method" => "GET",
                "Description" => "Show this Order",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/favorites/",
                "Method" => "GET",
                "Description" => "List my Favorites",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/favorites/{id}",
                "Method" => "GET",
                "Description" => "Show this Favorite",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/notifications",
                "Method" => "GET",
                "Description" => "List Notifications",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/notifications/{id}",
                "Method" => "GET",
                "Description" => "Show this Notification",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ]
        ];

        Endpoint::insert($endpoint);
    }
}
