<?php

namespace Database\Seeders;

use App\Models\Endpoint;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;

class EndpointSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $query = "
        INSERT INTO `endpoints` (`id`, `order`, `is_done`, `section`, `endpoint`, `method`, `header`, `body`, `description`, `response`, `requireAuth`, `comment`, `api_setup`, `created_at`, `updated_at`) VALUES
        (51, 1, 1, 'Authentications', '/api/user/register', 'POST', '', 'name, email, password', 'Register as User', '{\n    \"status\": true,\n    \"message\": \"User Created Successfully\",\n    \"token\": \"13|xGsqXDdF2c1eMVGOHjyPoksQEKkkXjdbQ7FbTwoh\"\n}', NULL, NULL, 1, NULL, '2023-04-15 03:48:19'),
        (52, 2, 1, 'Authentications', '/api/user/login', 'POST', '', 'email, password', 'Login as User', '{\n    \"status\": true,\n    \"message\": \"User Created Successfully\",\n    \"token\": \"13|xGsqXDdF2c1eMVGOHjyPoksQEKkkXjdbQ7FbTwoh\"\n}', NULL, NULL, 1, NULL, '2023-04-15 03:52:36'),
        (53, 3, 1, 'Authentications', '/api/user/logout', 'POST', 'bearer token', '', 'Logout as User', '{\n    \'status\' => true,\n    \'message\' => \'Successfully logged out\'\n}', NULL, NULL, 1, NULL, '2023-04-15 03:52:37'),
        (54, 4, 1, 'Authentications', '/api/company/register', 'POST', '', 'name, email, password', 'Register as Company', '{\n    \"status\": true,\n    \"message\": \"User Created Successfully\",\n    \"token\": \"14|RGwDjXDF2c1eMVGOHjyPoksQEKkkXjdbQ7FbTwoh\"\n}', NULL, NULL, 1, NULL, '2023-04-15 03:56:52'),
        (55, 5, 1, 'Authentications', '/api/company/login', 'POST', '', 'email, password', 'Login as Company', '{\n    \"status\": true,\n    \"message\": \"User Created Successfully\",\n    \"token\": \"14|RGwDjXDF2c1eMVGOHjyPoksQEKkkXjdbQ7FbTwoh\"\n}', NULL, NULL, 1, NULL, '2023-04-15 03:56:54'),
        (56, 6, 1, 'Authentications', '/api/company/logout', 'POST', 'bearer token', '', 'Logout as Company', '{\n    \'status\' => true,\n    \'message\' => \'Successfully logged out\'\n}', NULL, NULL, 1, NULL, '2023-04-15 03:56:55'),
        (58, 7, 1, 'Company Authenticated', '/api/auth/company/add-product', 'POST', 'bearer token', 'name, current_price, stock_left, keywords, description_ar, description_fr, description_en', 'Upload Product', '{\n    \'message\' => \'product added succesfully\',\n    \'product_id\' => 2\n}', NULL, NULL, 1, NULL, '2023-04-15 06:44:11'),
        (59, 8, 1, 'Company Authenticated', '/api/auth/company/product/{id}', 'GET', 'bearer token', '', 'Get this Product as Company', '{\n    \"product\": {\n        \"id\": 2,\n        \"name\": \"porductnam\",\n        \"current_price\": 153.3,\n        \"stock_left\": 26,\n        \"keywords\": \"aadfs,fsd ,ereok ,fdf\",\n        \"description_ar\": \"ewr\",\n        \"description_fr\": \"ewr\",\n        \"description_en\": \"ewr\"\n    },\n    \"company\": {\n        \"id\": 3,\n        \"name\": \"name\",\n        \"address\": null,\n        \"city\": null,\n        \"state\": null,\n        \"zip_code\": null,\n        \"phone_number\": null,\n        \"website\": null\n    }\n}', NULL, NULL, 1, NULL, '2023-04-15 07:11:35'),
        (60, 9, 1, 'Company Authenticated', '/api/auth/company/product/{id}', 'DELETE', 'bearer token', NULL, 'Delete this Product as Company', '{\n    \"message\": \"Product deleted successfully\"\n}', NULL, NULL, 1, NULL, '2023-04-15 07:11:45'),
        (61, 10, 0, 'Company Authenticated', '/api/auth/company/archive-product/{id}', 'POST', 'bearer token', '', 'Archive this Product as Company', 'not yet', NULL, NULL, 1, NULL, '2023-04-15 07:15:00'),
        (63, 11, 1, 'Company Authenticated', '/api/auth/company/add-service', 'POST', 'bearer token', 'name, current_price, keywords, description_ar, description_fr, description_en', 'Upload Service', '{\n    \"message\": \"service added succesfully\",\n    \"service_id\": 2\n}', NULL, NULL, 1, NULL, '2023-04-15 07:17:34'),
        (64, 12, 1, 'Company Authenticated', '/api/auth/company/service/{id}', 'GET', 'bearer token', '', 'Get this Service as Company', '{\n    \"service\": {\n        \"id\": 2,\n        \"name\": \"namee\",\n        \"current_price\": 653.33,\n        \"keywords\": \"kwer, jsdk, kf\",\n        \"description_ar\": \"en\",\n        \"description_fr\": \"en\",\n        \"description_en\": \"en\"\n    },\n    \"company\": {\n        \"id\": 9,\n        \"name\": \"name\",\n        \"address\": null,\n        \"city\": null,\n        \"state\": null,\n        \"zip_code\": null,\n        \"phone_number\": null,\n        \"website\": null\n    }\n}', NULL, NULL, 1, NULL, '2023-04-15 07:17:36'),
        (65, 13, 1, 'Company Authenticated', '/api/auth/company/service/{id}', 'DELETE', 'bearer token', '', 'Delete this Service as Company', '{\n    \"message\": \"Service deleted successfully\"\n}', NULL, NULL, 1, NULL, '2023-04-15 07:18:49'),
        (66, 14, 1, 'Company Authenticated', '/api/auth/company/product/{id}/archive', 'POST', 'bearer token', 'success', 'Archive this Service as Company', '{\n\'message\' => \'Product archived successfully\'\n}', NULL, NULL, 1, NULL, '2023-04-15 07:37:18'),
        (67, 16, 1, 'Company Authenticated', '/api/auth/company/getAllMyProducts', 'GET', 'bearer token', '', 'List my Products as company', '[ //might use paginations soon\n    {\n        \"id\": 3,\n        \"company_id\": 9,\n        \"name\": \"namee\",\n        \"current_price\": 653.33,\n        \"stock_left\": 0,\n        \"keywords\": \"kwer, jsdk, kf\",\n        \"description_ar\": \"en\",\n        \"description_fr\": \"en\",\n        \"description_en\": \"en\",\n        \"created_at\": \"2023-04-10T17:43:05.000000Z\",\n        \"updated_at\": \"2023-04-10T17:43:05.000000Z\"\n    }\n]', NULL, NULL, 1, NULL, '2023-04-15 07:36:00'),
        (68, 17, 1, 'Company Authenticated', '/api/auth/company/getAllMyServices', 'GET', 'bearer token', '', 'List my Services as company', '[ //might use paginations soon\n    {\n        \"id\": 3,\n        \"company_id\": 9,\n        \"name\": \"namee\",\n        \"description_ar\": \"en\",\n        \"description_fr\": \"en\",\n        \"description_en\": \"en\",\n        \"keywords\": \"kwer, jsdk, kf\",\n        \"current_price\": 653.33,\n        \"created_at\": \"2023-04-10T17:43:10.000000Z\",\n        \"updated_at\": \"2023-04-10T17:43:10.000000Z\"\n    }\n]', NULL, NULL, 1, NULL, '2023-04-15 07:37:14'),
        (69, 18, 1, 'Guest', '/api/service/get/{service_id}', 'GET', '', '', 'Show this Service details', '{\n    \"service\": {\n        \"id\": 3,\n        \"name\": \"namee\",\n        \"current_price\": 653.33,\n        \"keywords\": \"kwer, jsdk, kf\",\n        \"description_ar\": \"en\",\n        \"description_fr\": \"en\",\n        \"description_en\": \"en\"\n    },\n    \"company\": {\n        \"id\": 9,\n        \"name\": \"name\",\n        \"address\": null,\n        \"city\": null,\n        \"state\": null,\n        \"zip_code\": null,\n        \"phone_number\": null,\n        \"website\": null\n    }\n}', NULL, NULL, 1, NULL, '2023-04-15 07:42:43'),
        (70, 19, 1, 'Guest', '/api/service/latest', 'GET', '', '', 'Show Lastest Services', '{\n    \"services\": [\n        {\n            \"id\": 1,\n            \"name\": \"product name\",\n            \"current_price\": 169.22,\n            \"keywords\": \"keywords\",\n            \"description_ar\": \"description_ensdasd\",\n            \"description_fr\": \"description_ensdasd\",\n            \"description_en\": \"description_ensdasd\"\n        },\n        {\n            \"id\": 3,\n            \"name\": \"namee\",\n            \"current_price\": 653.33,\n            \"keywords\": \"kwer, jsdk, kf\",\n            \"description_ar\": \"en\",\n            \"description_fr\": \"en\",\n            \"description_en\": \"en\"\n        }\n    ]\n}', NULL, NULL, 1, NULL, '2023-04-17 05:07:17'),
        (71, 20, 1, 'Guest', '/api/service/search/{keywords}', 'GET', '', '', 'Search Service by keywords', '{\n    \"services\": [\n        {\n            \"id\": 1,\n            \"name\": \"product name\",\n            \"current_price\": 169.22,\n            \"keywords\": \"keywords\",\n            \"description_ar\": \"description_ensdasd\",\n            \"description_fr\": \"description_ensdasd\",\n            \"description_en\": \"description_ensdasd\"\n        },\n        {\n            \"id\": 3,\n            \"name\": \"namee\",\n            \"current_price\": 653.33,\n            \"keywords\": \"kwer, jsdk, kf\",\n            \"description_ar\": \"en\",\n            \"description_fr\": \"en\",\n            \"description_en\": \"en\"\n        }\n    ]\n}', NULL, NULL, 1, NULL, '2023-04-15 07:43:26'),
        (72, 21, 1, 'Guest', '/api/product/get/{product_id}', 'GET', '', '', 'Get this Product details', '{\n    \"product\": {\n        \"id\": 3,\n        \"name\": \"namee\",\n        \"current_price\": 653.33,\n        \"stock_left\": 0,\n        \"keywords\": \"kwer, jsdk, kf\",\n        \"description_ar\": \"en\",\n        \"description_fr\": \"en\",\n        \"description_en\": \"en\"\n    },\n    \"company\": {\n        \"id\": 9,\n        \"name\": \"name\",\n        \"address\": null,\n        \"city\": null,\n        \"state\": null,\n        \"zip_code\": null,\n        \"phone_number\": null,\n        \"website\": null\n    }\n}', NULL, NULL, 1, NULL, '2023-04-16 13:55:45'),
        (73, 22, 1, 'Guest', '/api/product/latest', 'GET', '', '', 'Get Lastest Products', '{\n    \"products\": [\n        {\n            \"id\": 1,\n            \"name\": \"product name\",\n            \"current_price\": 169.22,\n            \"stock_left\": 100,\n            \"keywords\": \"keywords\",\n            \"description_ar\": \"description_ensdasd\",\n            \"description_fr\": \"description_ensdasd\",\n            \"description_en\": \"description_ensdasd\"\n        },\n        {\n            \"id\": 3,\n            \"name\": \"namee\",\n            \"current_price\": 653.33,\n            \"stock_left\": 0,\n            \"keywords\": \"kwer, jsdk, kf\",\n            \"description_ar\": \"en\",\n            \"description_fr\": \"en\",\n            \"description_en\": \"en\"\n        }\n    ]\n}', NULL, NULL, 1, NULL, '2023-04-16 13:55:44'),
        (74, 23, 1, 'Guest', '/api/product/search/{keywords}', 'GET', '', '', 'Search Product by keywords', 'not yet', NULL, NULL, 1, NULL, '2023-04-17 05:07:32'),
        (75, 24, 0, 'Guest', '/api/category/{id}', 'GET', '', '', 'Get By Category', 'not yet', NULL, NULL, 0, NULL, '2023-04-12 20:17:25'),
        (76, 25, 0, 'Guest', '/api/company/{id}', 'GET', '', 'not yet', 'Show Company Details', 'success', NULL, NULL, 0, NULL, '2023-04-12 20:17:25'),
        (77, 26, 0, 'User Authenticated', '/api/auth/user/company/{id}/follow', 'POST', 'bearer token', 'not yet', 'Follow this Company', '{\n    \"message\": \"Followed Successfully\"\n}', NULL, NULL, 1, NULL, '2023-04-12 23:14:13'),
        (78, 27, 0, 'User Authenticated', '/api/auth/user/company/{id}/unfollow', 'POST', 'bearer token', 'not yet', 'unFollow this Company', 'success', NULL, NULL, 1, NULL, '2023-04-12 23:14:12'),
        (79, 28, 0, 'User Authenticated', '/api/auth/user/company/{id}/newsletter/follow', 'GET', 'bearer token', 'not yet', 'Follow this Newsletter', 'success', NULL, NULL, 0, NULL, '2023-04-12 20:17:25'),
        (80, 29, 0, 'User Authenticated', '/api/auth/user/company/{id}/newsletter/unfollow', 'GET', 'bearer token', 'not yet', 'unFollow this Newsletter', 'success', NULL, NULL, 0, NULL, '2023-04-12 20:17:25'),
        (81, 30, 0, 'User Authenticated', '/api/auth/user/product/{id}/favorite', 'GET', 'bearer token', 'not yet', 'Save this Product', '{\n    \"message\": \"product added to favorites list\"\n}', NULL, NULL, 1, NULL, '2023-04-12 23:14:11'),
        (82, 31, 0, 'User Authenticated', '/api/auth/user/product/{id}/unfavorite', 'GET', 'bearer token', 'not yet', 'unSave this Product', '{\n    \"message\": \"product is removed favorites list\"\n}', NULL, NULL, 1, NULL, '2023-04-12 23:14:11'),
        (83, 32, 0, 'User Authenticated', '/api/auth/user/product/{id}/add-review', 'GET', 'bearer token', 'not yet', 'Post Review in Product', 'success', NULL, NULL, 0, NULL, '2023-04-12 20:17:25'),
        (84, 33, 0, 'User Authenticated', '/api/auth/user/product/{id}/delete-review', 'GET', 'bearer token', 'not yet', 'get add services page', 'success', NULL, NULL, 0, NULL, '2023-04-12 20:17:25'),
        (85, 34, 0, 'User Authenticated', '/api/auth/user/service/{id}/favorite', 'GET', 'bearer token', 'not yet', 'Save this Service', '{\n    \"message\": \"service added to favorites list\"\n}', NULL, NULL, 1, NULL, '2023-04-12 23:14:10'),
        (86, 35, 0, 'User Authenticated', '/api/auth/user/service/{id}/unfavorite', 'GET', 'bearer token', 'not yet', 'unSave this Service', '{\n    \"message\": \"service is removed favorites list\"\n}', NULL, NULL, 1, NULL, '2023-04-12 23:14:08'),
        (87, 36, 0, 'User Authenticated', '/api/auth/user/service/{id}/book', 'GET', 'bearer token', 'not yet', 'date: (YYYY-MM-DD), subject, message', '{\n    \"message\": \"appoitment booked successfully\",\n    \"book\": {\n        \"service_id\": 1,\n        \"service_name\": \"product name\",\n        \"date\": \"2023-03-31T00:00:00.000000Z\",\n        \"subject\": \"sadsw\",\n        \"message\": \"jdkjf\"\n    }\n}', NULL, NULL, 1, NULL, '2023-04-12 23:14:07'),
        (88, 37, 0, 'User Authenticated', '/api/auth/user/service/{id}/unbook', 'GET', 'bearer token', 'not yet', 'Cancel Booking a Session', '{\n    \"message\": \"canceled booking successfully\"\n}', NULL, NULL, 1, NULL, '2023-04-12 23:14:06'),
        (89, 39, 0, 'User Authenticated', '/api/auth/user/orders', 'GET', 'bearer token', 'not yet', 'List my Orders', '{\n    \"message\": \"user orders list\",\n    \"orders\": [\n        {\n            \"id\": 1,\n            \"product_id\": 1,\n            \"user_id\": 2,\n            \"quantity\": 3,\n            \"ordered_price\": 12.3,\n            \"destination\": \"loca\",\n            \"location\": \"cation\",\n            \"order_status\": 1,\n            \"created_at\": \"2023-04-12T18:27:55.000000Z\",\n            \"updated_at\": \"2023-04-12T18:27:55.000000Z\"\n        }\n    ]\n}', NULL, NULL, 1, NULL, '2023-04-12 23:14:06'),
        (90, 40, 0, 'User Authenticated', '/api/auth/user/orders/{id}', 'GET', 'bearer token', 'not yet', 'Show this Order', '{\n    \"message\": \"user this order\",\n    \"orders\": {\n        \"id\": 1,\n        \"product_id\": 1,\n        \"user_id\": 2,\n        \"quantity\": 3,\n        \"ordered_price\": 12.3,\n        \"destination\": \"loca\",\n        \"location\": \"cation\",\n        \"order_status\": 1,\n        \"created_at\": \"2023-04-12T18:27:55.000000Z\",\n        \"updated_at\": \"2023-04-12T18:27:55.000000Z\"\n    }\n}', NULL, NULL, 1, NULL, '2023-04-12 23:14:06'),
        (91, 41, 0, 'User Authenticated', '/api/auth/user/favorites/products', 'GET', 'bearer token', 'not yet', 'List my Favorites', '{\n    \"message\": \"user s favorite products\",\n    \"products\": [\n        {\n            \"id\": 1,\n            \"company_id\": 7,\n            \"name\": \"product name\",\n            \"current_price\": 169.22,\n            \"stock_left\": 100,\n            \"keywords\": \"keywords\",\n            \"description_ar\": \"description_ensdasd\",\n            \"description_fr\": \"description_ensdasd\",\n            \"description_en\": \"description_ensdasd\",\n            \"created_at\": \"2023-03-20T23:47:41.000000Z\",\n            \"updated_at\": \"2023-03-20T23:47:41.000000Z\",\n            \"pivot\": {\n                \"user_id\": 2,\n                \"product_id\": 1\n            }\n        },\n        {\n            \"id\": 3,\n            \"company_id\": 9,\n            \"name\": \"namee\",\n            \"current_price\": 653.33,\n            \"stock_left\": 0,\n            \"keywords\": \"kwer, jsdk, kf\",\n            \"description_ar\": \"en\",\n            \"description_fr\": \"en\",\n            \"description_en\": \"en\",\n            \"created_at\": \"2023-04-10T17:43:05.000000Z\",\n            \"updated_at\": \"2023-04-10T17:43:05.000000Z\",\n            \"pivot\": {\n                \"user_id\": 2,\n                \"product_id\": 3\n            }\n        }\n    ]\n}', NULL, NULL, 1, NULL, '2023-04-12 23:14:05'),
        (92, 42, 0, 'User Authenticated', '/api/auth/user/favorites/products/{id}', 'GET', 'bearer token', 'not yet', 'Show this Favorite', '{\n    \"message\": \"user s favorite product\",\n    \"product\": {\n        \"id\": 1,\n        \"name\": \"product name\",\n        \"current_price\": 169.22,\n        \"stock_left\": 100,\n        \"keywords\": \"keywords\",\n        \"description_ar\": \"description_ensdasd\",\n        \"description_fr\": \"description_ensdasd\",\n        \"description_en\": \"description_ensdasd\"\n    },\n    \"company\": {\n        \"id\": 7,\n        \"name\": \"name\",\n        \"address\": null,\n        \"city\": null,\n        \"state\": null,\n        \"zip_code\": null,\n        \"phone_number\": null,\n        \"website\": null\n    }\n}', NULL, NULL, 1, NULL, '2023-04-12 23:14:04'),
        (93, 45, 0, 'User Authenticated', '/api/auth/user/notifications', 'GET', 'bearer token', 'not yet', 'List Notifications', 'setup not yet', NULL, NULL, 1, NULL, '2023-04-12 23:14:04'),
        (94, 46, 0, 'User Authenticated', '/api/auth/user/notifications/{id}', 'GET', 'bearer token', 'not yet', 'Show this Notification', 'setup not yet', NULL, NULL, 1, NULL, '2023-04-12 23:14:04'),
        (95, 38, 0, 'User Authenticated', '/api/auth/user/product/{id}/order', 'POST', 'bearer token', 'quantity, ordered_price, destination, location, order_status', 'Make an Order of this Product', '{\r\n    \"message\": \"Order created successfully\",\r\n    \"order\": {\r\n        \"id\": 1,\r\n        \"quantity\": \"3\",\r\n        \"ordered_price\": \"12.3\",\r\n        \"order_status\": \"1\",\r\n        \"location\": \"cation\",\r\n        \"destination\": \"loca\"\r\n    }\r\n}', NULL, NULL, 1, NULL, '2023-04-12 23:14:03'),
        (96, 43, 0, 'User Authenticated', '/api/auth/user/favorite/services', 'GET', 'bearer token', NULL, 'Get list of user\'s fav services', '{\n    \"message\": \"user s favorite service\",\n    \"service\": [\n        {\n            \"id\": 1,\n            \"company_id\": 7,\n            \"name\": \"product name\",\n            \"description_ar\": \"description_ensdasd\",\n            \"description_fr\": \"description_ensdasd\",\n            \"description_en\": \"description_ensdasd\",\n            \"keywords\": \"keywords\",\n            \"current_price\": 169.22,\n            \"created_at\": \"2023-03-20T23:49:44.000000Z\",\n            \"updated_at\": \"2023-03-20T23:49:44.000000Z\",\n            \"pivot\": {\n                \"user_id\": 2,\n                \"service_id\": 1\n            }\n        },\n        {\n            \"id\": 3,\n            \"company_id\": 9,\n            \"name\": \"namee\",\n            \"description_ar\": \"en\",\n            \"description_fr\": \"en\",\n            \"description_en\": \"en\",\n            \"keywords\": \"kwer, jsdk, kf\",\n            \"current_price\": 653.33,\n            \"created_at\": \"2023-04-10T17:43:10.000000Z\",\n            \"updated_at\": \"2023-04-10T17:43:10.000000Z\",\n            \"pivot\": {\n                \"user_id\": 2,\n                \"service_id\": 3\n            }\n        }\n    ]\n}', NULL, NULL, 1, NULL, '2023-04-12 23:14:02'),
        (97, 44, 0, 'User Authenticated', '/api/auth/user/favorite/services/{id}', 'GET', 'bearer token', NULL, 'Get this fav Service', '{\n    \"message\": \"user s favorite service\",\n    \"service\": {\n        \"id\": 1,\n        \"name\": \"product name\",\n        \"current_price\": 169.22,\n        \"keywords\": \"keywords\",\n        \"description_ar\": \"description_ensdasd\",\n        \"description_fr\": \"description_ensdasd\",\n        \"description_en\": \"description_ensdasd\"\n    },\n    \"company\": {\n        \"id\": 7,\n        \"name\": \"name\",\n        \"address\": null,\n        \"city\": null,\n        \"state\": null,\n        \"zip_code\": null,\n        \"phone_number\": null,\n        \"website\": null\n    }\n}', NULL, NULL, 1, NULL, '2023-04-12 23:14:01'),
        (98, 15, 1, 'Company Authenticated', '/api/auth/company/product/{id}/activate', 'POST', 'bearer token', NULL, 'Activate this Product', '{\n\'message\' => \'Product activated successfully\'\n}', NULL, NULL, 1, NULL, '2023-04-15 07:40:59');
        ";

        DB::insert($query);
    }
}

/*
$endpoint = [
            [
                "section" => "Authentications",
                "Endpoint" => "/api/user/register",
                "Method" => "POST",
                "Description" => "Register as User",
                "Header" => "",
                "Body" => "name, email, password",
                "Response" => "Bearer Token",
            ],
            [
                "section" => "Authentications",
                "Endpoint" => "/api/user/login",
                "Method" => "POST",
                "Description" => "Login as User",
                "Header" => "",
                "Body" => "email, password",
                "Response" => "Bearer Token",
            ],
            [
                "section" => "Authentications",
                "Endpoint" => "/api/user/logout",
                "Method" => "POST",
                "Description" => "Logout as User",
                "Header" => "bearer token",
                "Body" => "",
                "Response" => "Success",
            ],
            [
                "section" => "Authentications",
                "Endpoint" => "/api/company/register",
                "Method" => "POST",
                "Description" => "Register as Company",
                "Header" => "",
                "Body" => "name, email, password",
                "Response" => "Bearer Token",
            ],
            [
                "section" => "Authentications",
                "Endpoint" => "/api/company/login",
                "Method" => "POST",
                "Description" => "Login as Company",
                "Header" => "",
                "Body" => "email, password",
                "Response" => "Bearer Token",
            ],
            [
                "section" => "Authentications",
                "Endpoint" => "/api/company/logout",
                "Method" => "POST",
                "Description" => "Logout as Company",
                "Header" => "bearer token",
                "Body" => "",
                "Response" => "Success",
            ],
            [
                "section" => "Company Authenticated",
                "Endpoint" => "/api/auth/company/add-products",
                "Method" => "GET",
                "Description" => "Get add Products Page",
                "Header" => "bearer token",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "Company Authenticated",
                "Endpoint" => "/api/auth/company/add-products",
                "Method" => "POST",
                "Description" => "Upload Product",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "Company Authenticated",
                "Endpoint" => "/api/auth/company/product/{id}",
                "Method" => "GET",
                "Description" => "Get this Product as Company",
                "Header" => "bearer token",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "Company Authenticated",
                "Endpoint" => "/api/auth/company/product/{id}",
                "Method" => "DELETE",
                "Description" => "Delete this Product as Company",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "Company Authenticated",
                "Endpoint" => "/api/auth/company/archive-product/{id}",
                "Method" => "POST",
                "Description" => "Archive this Product as Company",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "Company Authenticated",
                "Endpoint" => "/api/auth/company/add-service",
                "Method" => "GET",
                "Description" => "Get add Services Page",
                "Header" => "bearer token",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "Company Authenticated",
                "Endpoint" => "/api/auth/company/add-service",
                "Method" => "POST",
                "Description" => "Upload Service",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "Company Authenticated",
                "Endpoint" => "/api/auth/company/service/{id}",
                "Method" => "GET",
                "Description" => "Get this Service as Company",
                "Header" => "bearer token",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "Company Authenticated",
                "Endpoint" => "/api/auth/company/service/{id}",
                "Method" => "DELETE",
                "Description" => "Delete this Service as Company",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "Company Authenticated",
                "Endpoint" => "/api/auth/company/archive-service/{id}",
                "Method" => "POST",
                "Description" => "Archive this Service as Company",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "Company Authenticated",
                "Endpoint" => "/api/auth/company/getAllProducts",
                "Method" => "GET",
                "Description" => "List my Products as company",
                "Header" => "bearer token",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "Company Authenticated",
                "Endpoint" => "/api/auth/company/getAllServices",
                "Method" => "GET",
                "Description" => "List my Services as company",
                "Header" => "bearer token",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "Guest",
                "Endpoint" => "/api/service/get/{service_id}",
                "Method" => "GET",
                "Description" => "Show this Service details",
                "Header" => "",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "Guest",
                "Endpoint" => "/api/service/latest",
                "Method" => "GET",
                "Description" => "Show Lastest Services",
                "Header" => "",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "Guest",
                "Endpoint" => "/api/service/search/{keywords}",
                "Method" => "GET",
                "Description" => "Search Service by keywords",
                "Header" => "",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "Guest",
                "Endpoint" => "/api/product/get/{product_id}",
                "Method" => "GET",
                "Description" => "Get this Product details",
                "Header" => "",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "Guest",
                "Endpoint" => "/api/product/latest",
                "Method" => "GET",
                "Description" => "Get Lastest Products",
                "Header" => "",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "Guest",
                "Endpoint" => "/api/product/search/{keywords}",
                "Method" => "GET",
                "Description" => "Search Product by keywords",
                "Header" => "",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "Guest",
                "Endpoint" => "/api/category/{id}",
                "Method" => "GET",
                "Description" => "Get By Category",
                "Header" => "",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "Guest",
                "Endpoint" => "/api/company/{id}",
                "Method" => "GET",
                "Description" => "Show Company Details",
                "Header" => "",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/company/{id}/follow",
                "Method" => "POST",
                "Description" => "Follow this Company",
                "Header" => "bearer token",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/company/{id}/unfollow",
                "Method" => "POST",
                "Description" => "unFollow this Company",
                "Header" => "bearer token",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/company/{id}/newsletter/follow",
                "Method" => "GET",
                "Description" => "Follow this Newsletter",
                "Header" => "bearer token",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/company/{id}/newsletter/unfollow",
                "Method" => "GET",
                "Description" => "unFollow this Newsletter",
                "Header" => "bearer token",
                "Body" => "",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/product/{id}/favorite",
                "Method" => "GET",
                "Description" => "Save this Product",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/product/{id}/unfavorite",
                "Method" => "GET",
                "Description" => "unSave this Product",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/product/{id}/add-review",
                "Method" => "GET",
                "Description" => "Post Review in Product",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/product/{id}/delete-review",
                "Method" => "GET",
                "Description" => "get add services page",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/service/{id}/favorite",
                "Method" => "GET",
                "Description" => "Save this Service",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/service/{id}/unfavorite",
                "Method" => "GET",
                "Description" => "unSave this Service",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/service/{id}/book",
                "Method" => "GET",
                "Description" => "Book a Session",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/service/{id}/unbook",
                "Method" => "GET",
                "Description" => "Cancel Booking a Session",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/orders",
                "Method" => "GET",
                "Description" => "List my Orders",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/orders/{id}",
                "Method" => "GET",
                "Description" => "Show this Order",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/favorites/",
                "Method" => "GET",
                "Description" => "List my Favorites",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/favorites/{id}",
                "Method" => "GET",
                "Description" => "Show this Favorite",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/notifications",
                "Method" => "GET",
                "Description" => "List Notifications",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ],
            [
                "section" => "User Authenticated",
                "Endpoint" => "/api/auth/user/notifications/{id}",
                "Method" => "GET",
                "Description" => "Show this Notification",
                "Header" => "bearer token",
                "Body" => "success",
                "Response" => "success",
            ]
        ];

        Endpoint::insert($endpoint);
        */